MODULES = ['create_trg_images']
MODE = 'samples'

DATASETTEMPLATE = 'trg'

DATASETFOLDER = '../' + DATASETTEMPLATE + '/'
FOLDER = DATASETFOLDER + MODE + '/'
BINFOLDER = DATASETFOLDER + MODE + 'bin/'
LABELSFOLDER = DATASETFOLDER + MODE + 'labels/'

LABELS = MODE + '.json'
LABELSPATH = FOLDER + LABELS

MIN_OBJECT_WIDTH = 4
MIN_OBJECT_HEIGHT = 4
RECTS_DILATION = (7, 6)

