MODULES = ['prepare_samples', 'create_trg_images', 'main']
MODE = 'samples'

DATASETTEMPLATE = 'trg'

DATASETFOLDER = '../' + DATASETTEMPLATE + '/'
FOLDER = DATASETFOLDER + MODE + '/'
BINFOLDER = DATASETFOLDER + MODE + 'bin/'
LABELSFOLDER = DATASETFOLDER + MODE + 'labels/'

LABELS = MODE + '.json'
LABELSPATH = DATASETFOLDER + LABELS
CACHEDLABELSPATH = LABELSFOLDER + 'cached_' + LABELS
CACHEDIDBYFILENAMEPATH = LABELSFOLDER + 'cached_id_by_file_name_' + LABELS

MIN_OBJECT_WIDTH = 4
MIN_OBJECT_HEIGHT = 4
RECTS_DILATION = (7, 6)

